version: '2'
services:
  api:
    build:
      context: ./packages/api/
    volumes:
      - ./packages/api/:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - '4000:4000'

  app:
    build:
      context: ./packages/app/
    volumes:
      - ./packages/app/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    ports:
      - '3000:3000'
